# Discord Linked #
## Link your discord to your minecraft server #
# Created by SamVolvo and Thijs_D #



DC_Token: ""

# General settings
general:
  joinMessages: true
  chatSync: true
  joinVerification: true

minecraft:
  needDiscord: true
  # Sends the commands send in Minecraft to the Discord Channel that have been set
  sendCommands: true

discord:
  # Sends the commands send in discord to the Online Minecraft players that have the permission
  sendCommands: true
  guildId: ""
  chatChannel: ""
  adminChannel: ""