# Discord Linked #
## Link your discord to your minecraft server #
# Created by SamVolvo and Thijs_D #



DC_Token: ""

# General settings
general:
  joinMessages: true
  chatSync: true
  joinVerification: true

minecraft:
